import type { Metadata } from "next";
import "../styles/globals.css";
import { satoshiRegular, satoshiLight } from "../styles/fonts";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Menu from "@/components/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiLight.className} bg-background text-text`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
